### ISSUE TITLE
添加类似 QT_VERSION 的版本判断宏定义

### ISSUE THREAD

**Issue by meishuai291** [morpheslee/sipesc#10]
希望平台能增加类似 QT_VERSION 这样的版本定义宏命令，这样就可以编写对应不同版本的代码，编译时自动选择对应的代码条件编译，可以为开发带来很大的便利。

**Comment by sipesc** [comment]
在mextmgrcore.h文件中添加了M_EXTMGR_CORE_VERSION定义。
在mextmgrui.h文件中添加了M_EXTMGR_UI_VERSION定义。
在mextmgrdesigner.h文件中添加了M_EXTMGR_DESIGNER_VERSION定义。
在mextmgrpkgbuilder.h文件中添加了M_EXTMGR_PKGBUILDER_VERSION定义。
在mextmgrspt.h文件中添加了M_EXTMGR_SPT_VERSION定义。

详细信息请查看相应的头文件。
