### ISSUE TITLE
新安装包快捷方式目标路径

### ISSUE THREAD

**Issue by meishuai291** [morpheslee/sipesc#11]
1. 新安装包管理器，修改路径限制 19 字符，不知什么原因？不让往二级目录安装吗？
2. 新安装包管理器，修改安装路径后，桌面快捷方式的仍然是 C:\MinGW64，并没有更新到新的安装位置

**Comment by sipesc** [comment]
1. 由于软件包都是在Linux下交叉编译的，生成的可执行文件中包含大量的绝对路径信息如/usr/x86_64-w64-mignw32或/usr/i686-w64-mingw32这样的信息，这些信息是程序运行时使用的，安装到windows中后，这些路径不存在，必须在安装过程中修正为安装路径。而这些信息是在程序内写死的，修改时路径不能超过原来的长度，因此对于32位版本，最大长度为/usr/i686-w64-mingw32的长度即19个字符，对于64位，最大长度为/usr/x86_64-w64-mingw32的长度即21个字符。如果超过这个长度，修正后的可执行文件将不可用。
2. 修改安装路径后，如果没有重新安装软件包，软件包的安装位置并不会自动改变。可能好的解决办法是修改了安装路径后自动移动所有已安装软件包到新的安装路径，不过这将话费很长的时间，你有什么好的建议吗？

**Comment by meishuai291** [comment]
2. 我不是指安装后更换。我是指，新安装前就将安装目录更改到d盘。安装之后桌面快捷方式仍然指向c盘。

**Comment by meishuai291** [comment]
2. 刚才再次打开管理器，提示正在切换系统架构，桌面快捷方式重新生成了。这次指向的位置正确了。
那也就是安装时生成的快捷方式路径不正确。
还有，我嫌快捷方式多，乱，因此手动删除了快捷方式，但是当我再次打开管理器，快捷方式又被重新创建出来了。

**Comment by sipesc** [comment]
已修正，安装新版本软件包管理器即可。
