### ISSUE TITLE
插件设计器建议

### ISSUE THREAD

**Issue by meishuai291** [morpheslee/sipesc#13]
插件设计器一崩溃，*.sipplugin内容就全丢了。
能否在保存过程中，先保留一个备份文件，当保存成功时，再将备份文件删除。

**Comment by sipesc** [comment]
这个问题是由于在生成插件XML之前就打开文件造成的，而在生成插件XML过程中发生崩溃，从而导致没有写入正确的数据到文件中。现在改为先生成插件XML，再打开文件写入。这样就可以避免这个问题了。但是生成插件XML过程发生的崩溃目前还没有找到原因。
