### ISSUE TITLE
软件包管理器打开很慢

### ISSUE THREAD

**Issue by meishuai291** [morpheslee/sipesc#16]
每次打开软件包管理器，需要等待一分钟左右才能正常使用。（开发环境，软件安装了一多半）

**Comment by sipesc** [comment]
可能是安装了apache2造成的。启动过程中会检查各软件包状态，而apache2由于是系统服务，检查过程中会查询系统服务状态，因此会比较缓慢。会考虑使用别的方法实现，提高效率。
