### ISSUE TITLE
项目浏览器 不更新

### ISSUE THREAD

**Issue by meishuai291** [morpheslee/sipesc#19]
在项目浏览器中，先进行删除操作，再进行添加操作是，项目浏览器 **不更新或更新错误**。

例如，创建一个cmake项目，然后进行以下操作：
第一步 添加一个源文件 aaa， **成功**
第二步 删除源文件 aaa，  **成功**
第三步 添加源文件 bbb， **失败**

**Comment by sipesc** [comment]
已经解决
