### ISSUE TITLE
插件加载

### ISSUE THREAD

**Issue by meishuai291** [morpheslee/sipesc#3]
在 workbench.sipapp 定义加载插件项后，平台配置界面中，仅显示绿色盾牌，前面并没有勾选。
而通过配置页面勾选加载的插件，既有绿色盾牌也有对勾。

是有意这么设置的吗？

![default](https://cloud.githubusercontent.com/assets/8476208/21666671/1adb6592-d32e-11e6-8a68-6d95116cd620.PNG)

**Comment by sipesc** [comment]
workbench.sipapp是系统文件，最好不要直接修改这个文件，而是在平台配置页面进行配置。修改了workbench.sipapp文件，在平台内是无法看到相关设置的，平台内看到的是当前工作空间的设置。你这样修改workbench.sipapp文件目的又是什么呢？

**Comment by meishuai291** [comment]
修改workbench.sipapp文件目的：打开平台后可以直接使用，不需再进行配置。

比如我需要有限元功能，我通过 修改workbench.sipapp和在快捷方式中添加  --perspective=org.sipesc.ui.perspective.fems 就可以实现，用户第一次启动平台后，即是可直接使用的界面。

如果第一次使用平台，需要打开后加载插件，打开相关panel等等，界面不太友好。

**Comment by sipesc** [comment]
最好不要这样做，可以复制workbench.sipapp文件到新的名称，然后再做修改。这样可以添加自己的设置，可以修改启动图片（splash），也可以添加其他功能。如果有问题也可以快速回复。

**Comment by meishuai291** [comment]
问题是 mextmgr-workbench.exe 已经写死了，我只能使用 workbench.sipapp。
或者你再提供一个仅仅内部定义环境变量的 启动程序。可以自由选择 sipapp。

**Comment by sipesc** [comment]
那么就直接使用mextmgr-launcher来启动就可以了。

**Comment by sipesc** [comment]
明白了，那就这样做吧，你这个用法是针对特定使用情况的，可以！
