### ISSUE TITLE
新进程执行py脚本

### ISSUE THREAD

**Issue by meishuai291** [morpheslee/sipesc#4]
如下图，使用 “新进程” + “调试版本” 执行脚本时，提示 启动 python 脚本加载器程序失败。可能是没有修改为 **launcher -d** 而仍为 **launcherd**
![1](https://cloud.githubusercontent.com/assets/8476208/21668673/031a7928-d33f-11e6-9c95-d5a1830570d7.PNG)

**Comment by sipesc** [comment]
问题已经解决，原因正如前面说述，没有将"mextmgr-clauncherd"改为"mextmgr-clauncher -d"，从而导致这个错误。
