### ISSUE TITLE
MDataModel 使用clear方法时崩溃

### ISSUE THREAD

**Issue by meishuai291** [morpheslee/sipesc#6]
测试代码：

	MDataModel model = dbManager.createDataModel();
	isOk = model.open(db, "SiPESC.PVGH");
	Q_ASSERT(isOk);

	MDataModel model2 = dbManager.createDataModel();
	isOk = model2.open(model, "MMM");
	Q_ASSERT(isOk);
	model2.close();

	model.clear();

**Comment by meishuai291** [comment]
李老师：
    此问题是否已经修复？

**Comment by sipesc** [comment]
目前正忙于软件打包工作，解决后会在这里标记状态的。

**Comment by sipesc** [comment]
已修复
