### ISSUE TITLE
软件包管理器卸载dbus软件包时删除dbus-daemon失败

### ISSUE THREAD

**Issue by meishuai291** [morpheslee/sipesc#9]
由于 dbus-daemon 是常驻进程，卸载dbus软件包时，其正在运行，导致无法彻底卸载。

**Comment by sipesc** [comment]
在新的软件包管理器中，针对这个问题，采用Win32 API函数，对系统内正在运行的进程进行遍历，找到正在运行的程序或正在使用文件的进程(对于DLL文件会存在这种情况)，提示用户是否要关闭进程，如果用户确认，则终止找到的进程，然后再次尝试删除。如果删除失败，则采用循环尝试删除，直到成功或用户选择放弃。

**Comment by sipesc** [comment]
已经解决，新发布版本已可按用户要求终止相应的进程。
